pttStockUrl: https://www.ptt.cc/bbs/Stock/index.html
keyTransform:
      推文: push
      網址: url
      作者: author
      標題: title
      時間: time
celebrityList:
      [
            a000000000,
            f204137,
            bear410040, 
            phcebus,
            test520,
            zesonpso,
            tradow,
            robertshih,
            leondemon,
            Capufish,
            Djuda,
            book1999,
            waitrop,
            MoonCode,
            a0808996,
            tompi,
            sky22485816,
            ffaarr,
            peter5479,
            mytropicfish,
            kero8give,
            smallworld,
            WADE0616,
            wen12305,
            youbo0627,
            moboo,
            minazukimaya,
            guilty13,
      ]
checkPageNum: 5
requestInterval: 5